title: Communicator
baseUri: 'http://localhost:80'
version: 1

/:
  displayName: Index
  description: Server index page
  get:
    responses:
      '200':
        body:
          text/html:

/getconfiglist:
  displayName: GetConfigList
  description: Returns list of configurations
  get:
    responses:
      '200':
        body:
          application/json:
            example: |
            {
              "configurations": [ "config","test" ]
            }

/getallparams:
  displayName: GetAllParams
  description: Returns parameters of selected configuration
  get:
    responses:
      '200':
        body:
          application/json:
            example: |
            {
              "databits": "8",
              "flowcontrol": "None",
              "parity": "None",
              "speed": "115200",
              "stopbits": "1"
            }

/getconfigparams:
  displayName: GetConfigParams
  description: Returns lists of all parameters
  get:
    body:
      text/plain:
        type: string
        example: config=config
    responses:
      '200':
        body:
          application/json:
            example: |
            {
              "databits": ["7","8"],
              "flowcontrol": ["None","Yes"],
              "parity": ["None","Odd","Even"],
              "speed": ["9600","19200","115200"],
              "stopbits": ["1","2"]
            }

/addnewconfig:
  displayName: AddNewConfig
  description: Add new configuration
  post:
    body:
      text/plain:
        type: string
        example: config=config
    responses:
      '200':
        body:
          application/json:
            examples:
              exOk: |
              {
                "result": "Ok"
              }
              exErr: |
              {
                "result": "Error"
              }

/deleteconfig:
  displayName: DeleteConfig
  description: Delete selected configuration
  get:
    body:
      text/plain:
        type: string
        example: config=config
    responses:
      '200':
        body:
          application/json:
            example: |
            {
              "result": "Ok"
            }

/saveconfigparams:
  displayName: SaveConfig
  description: Save new parameters or name for selected configuration
  post:
    body:
      text/plain:
        type: string
        example: config=config&config_new_name=new_name
    responses:
      '200':
        body:
          application/json:
            examples:
              exOk: |
              {
                "result": "Ok"
              }
              exErr: |
              {
                "result": "Error"
              }

/api:
  /getportslist:
    displayName: GetPortsList
    description: Returns list of available COM ports
    get:
      responses:
        '200':
          body:
            application/json:
              example: |
              {
                "ports": [ "COM85","COM88" ]
              }

  /openport:
    displayName: OpenPort
    description: Open selected COM port
    post:
      body:
        text/plain:
          type: string
          example: port=COM88&config_speed=9600&config_databits=8&config_parity=None&config_stopbits=2&config_flowcontrol=None
      responses:
        '200':
          body:
            application/json:
              examples:
                exOk: |
                {
                  "result": "Ok"
                }
                exErr: |
                {
                  "result": "Error"
                }

  /closeport:
    displayName: ClosePort
    description: Close selected COM port
    post:
      body:
        text/plain:
          type: string
          example: port=COM88
      responses:
        '200':
          body:
            application/json:
              examples:
                exOk: |
                {
                  "result": "Ok"
                }
                exErr: |
                {
                  "result": "Error"
                }

  /sendtoport:
    displayName: SendToPort
    description: Send data to selected COM port
    post:
      body:
        text/plain:
          type: string
          example: port=COM88&cmd=0x00ff
      responses:
        '200':
          body:
            application/json:
              examples:
                exOk: |
                {
                  "result": "Ok"
                }
                exErr: |
                {
                  "result": "Error"
                }

  /readfromport:
    displayName: ReadFromPort
    description: Read data from selected COM port
    post:
      body:
        text/plain:
          type: string
          example: port=COM88
      responses:
        '200':
            application/json:
              examples:
                exOk: |
                {
                  "received": "0x01",
                  "result": "Ok"
                }
                exErr: |
                {
                "received": "",
                  "result": "Error"
                }
